before_script:
  - sudo apt-add-repository ppa:swi-prolog/devel -y
  - sudo apt-get update -q
  - sudo apt-get install swi-prolog-nox

script: swipl -t "load_test_files([]), run_tests." -s logical_numbers.pl
